-- establish database and create key schemas for each layer 

USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS STOCK_ANALYSIS;

CREATE SCHEMA IF NOT EXISTS STOCK_ANALYSIS.INGEST;
CREATE SCHEMA IF NOT EXISTS STOCK_ANALYSIS.MODEL;
CREATE SCHEMA IF NOT EXISTS STOCK_ANALYSIS.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS STOCK_ANALYSIS.SERVE;

USE DATABASE STOCK_ANALYSIS;
USE SCHEMA INGEST;


-- create stage for data ingestion
CREATE OR REPLACE STAGE stock_stage;

-- create a common file format for cleanliness
CREATE OR REPLACE FILE FORMAT ff_csv
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null', 'None');

LIST @STOCK_ANALYSIS.INGEST.STOCK_STAGE;
  